model_path: "/home/ruomeng/model/meta-llama/Llama-3.2-1B"
model_name: "Llama-3.2-1B"
epochs: 1000
batch_size: 8
block_size: 1024
lr: 1e-4
betas: [0.9, 0.95]
dtype: "bfloat16"
weight_decay: 0.01
seed: 42
eval_interval: 50
grad_clip: 1.0
peft: False